version: '3.4'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis

  projectLp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    container_name: app