spring:
  application:
    name: ProJectLP

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate.format_sql: true

  main:
    allow-bean-definition-overriding: true


  cache:
    type: redis
  data:
    redis:
      host: update
      port: 6379
      password: update
#      username: update
      ssl:
        enabled: true
    a:
      redis:
        index: 0
    b:
      redis:
        index: 1
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      resolve-lazily: true

  cloud:
    aws:
      credentials:
        access-key: update
        secret-key: update
      region:
        static: ap-northeast-2
      s3:
        bucket: projectmiluju

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: update
    username: update
    password: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: update
    password: update
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
    auth-code-expiration-millis: 1800000

jwt:
  secret: update

multipartfile:
  url: .s3.ap-northeast-2.amazonaws.com/

sentry:
  traces-sample-rate: 1.0
  dsn: update
  exception-resolver-order: -2147483647
